name: CI Pipeline

on:
  push:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: DockerHub 로그인
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Docker 이미지 빌드 및 푸시
      run: |
        docker build -t ${{ secrets.DOCKER_USERNAME }}/dododocs-fe:latest .
        docker push ${{ secrets.DOCKER_USERNAME }}/dododocs-fe:latest

    - name: 컨테이너 실행 및 테스트
      run: |
        docker run -d -p 3000:3000 --rm ${{ secrets.DOCKER_USERNAME }}/dododocs-fe:latest &
        sleep 20  # 애플리케이션이 시작될 시간을 줍니다.
        # 기본 경로에서 서버 확인
        HTTP_STATUS=$(curl -o /dev/null -s -w "%{http_code}" http://localhost:3000/)
        if [ "$HTTP_STATUS" -ne 200 ] && [ "$HTTP_STATUS" -ne 404 ]; then
          echo "Unexpected HTTP status: $HTTP_STATUS"
          exit 1
        fi
        echo "Server is running with HTTP status: $HTTP_STATUS"