name: Krampoline Notification

on: 
  push:
    branches:
      - main

jobs:
  noti:
    runs-on: ubuntu-latest
    steps:
    - uses: sarisia/actions-status-discord@v1.15.0
      if: always()
      with:
        webhook: ${{ secrets.DISCORD_WEBHOOK_FULLSTACK }}
        title: "❗️ Remind : 크램폴린 CI/CD ❗️"
        description: |
          크램폴린에서 D2Hub 빌드와 Kargo 배포를 진행해주세요.
          [여기](https://krampoline-ide.kakao.com/organization/org_ffYH4PrzrR6et39c2k/dashboard)를 눌러 크램폴린IDE로 들어가세요!
        color: 0xff6d44
