name: Prod CI on release

on:
  release:
    types:
      - published

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build and Tag Docker Image
        env:
          ECR_URI: ${{ secrets.ECR_URI }}
          TAG: ${{ github.event.release.tag_name }}
        run: |
          echo "Using tag: $TAG"
          docker build -t $ECR_URI:$TAG .

      - name: Push Docker Image to Amazon ECR
        env:
          ECR_URI: ${{ secrets.ECR_URI }}
          TAG: ${{ github.event.release.tag_name }}
        run: |
          docker push $ECR_URI:$TAG
